apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleet-manager.name" . }}
  labels: {{- include "fleet-manager.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "fleet-manager.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
